#!/bin/bash

# Install NDN Forwarder
git clone --recursive https://github.com/named-data/NFD
cd NFD
git checkout master
./waf configure
./waf
./waf install
cd ..
rm -Rf NFD

# Install ndn-tools
git clone --recursive https://github.com/named-data/ndn-tools.git
cd ndn-tools
./waf configure
./waf
./waf install
cd ..
rm -Rf ndn-tools

# Initial NFD Configuration
cp /usr/local/etc/ndn/nfd.conf.sample /usr/local/etc/ndn/nfd.conf
ndnsec-keygen /`whoami` | ndnsec-install-cert -
mkdir -p /usr/local/etc/ndn/keys
ndnsec-cert-dump -i /`whoami` > default.ndncert
mv default.ndncert /usr/local/etc/ndn/keys/default.ndncert
